version: '2'
services:
  web:
    build: .
    ports:
     - "18080:8080"
    links:
     - cache
  cache:
    image: redis:4.0
    ports:
         - "6379:6379"
  db:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=pwd"
    ports:
      - "1433:1433"
